[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aptos-move-analyzer"
version = "1.0.0"
description = "Aptos Move 项目索引与查询的轻量 Python 库"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "tree-sitter>=0.20.0",
]

[project.scripts]
aptos-move-analyzer = "aptos_move_analyzer.cli:main"
